### ISSUE TITLE
ChromeOS-Flex Dev mode - cannot enter VT2 terminal 

### ISSUE THREAD

**Issue by csp5me** [sebanc/linuxloops#11]
Hi, 

would like to give a shoutout to your team making dual boot of Chrome OS Flex possible with this tool. Really very helpful.

So I installed Flex in dev mode and can boot from a linux grub file.
All in ChromeOS seems to work well, also updates.
Ctrl+T to enter crosh and going into shell works also. So assume dev mode is set on.

However to go to VT2  / VT3 .. [ctrl+alt+F2 /F3 etc. ] gives a black screen.
Also cannot go back [ctrl+alt+F1] to multi window mode.

Only option is to shutdown the laptop.

**Comment by sebanc** [comment]
Hi,

Unless I am mistaken, this is the standard behaviour when you enable dev mode with ChromeOS-Flex, even when ChromeOS-Flex is installed through the official installer. My understanding of this issue is that it is related to missing VT configs in the ChromeOS-Flex kernel.

However, I think you can still use sudo from crosh shell if you update to dev-channel.
