### ISSUE TITLE
MacBook Air has no way to connect to network in live environment

### ISSUE THREAD

**Issue by Cam396** [sebanc/linuxloops#12]
I tried to connect to wifi in the live installer after using rufus to copy the image to my usb drive. However, It wouldn't show any network cards. I tried to add a wifi network manually, but that didn't work either.
INFO:
MacBookAir7,2 (a1446)
intel wifi chip ???

**Comment by Cam396** [comment]
UPDATE:
After some digging, I found that the package `bcmwl-kernel-source` or `firmware-b43-installer` needs to be in the live enviroment for wifi to work. (Btw those are `apt` packages, pacman or other package managers might have it as something else.)

**Comment by sebanc** [comment]
Unfortunately, I cannot add those packages by default as they will break wifi for orher users due to the below modprobe conf:
```
blacklist b43
blacklist b43legacy
blacklist b44
blacklist bcma
blacklist brcm80211
blacklist brcmsmac
blacklist ssb
```

However, you can generate a linuxloops live image including your wifi drivers from WSL2 using the command:
```
sudo bash linuxloops -distro Debian -env Cinnamon -dst /mnt/c/Users/"your username"/Downloads/linuxloops_live_custom.img -u -a -b -c "file-roller firefox-esr gedit gparted evince bcmwl-kernel-source firmware-b43-installer"
```

If you install a linux distro, you will also need to specify those packages or their equivalents in the corresponding distro in the additional packages list.

**Comment by Cam396** [comment]
I understand that, but would it be possible to add a boot profile or something of the sort so the default option for other users still works, but Mac users can also have a working profile? If it isn't that's fine too.

**Comment by sebanc** [comment]
I have found a way to implement this. You can try the latest linuxloops live image and choose "Debian (with additional WiFi drivers)" from the grub boot menu.

**Comment by Cam396** [comment]
Thank you!
