### ISSUE TITLE
refind bootloader config?

### ISSUE THREAD

**Issue by emilieroberts** [sebanc/linuxloops#14]
This project is awesome, thank you. I am hoping to boot ChromeOS-Flex from refind. Have you tried this? Any hints for converting the grub.cfg to a refind config?

**Comment by sebanc** [comment]
refind is a very nice tool but they have unfortunately not implemented a loopback device mechanism similar to the one that exist in grub and that linuxloops uses to boot disk images. There were a few discussions about this but there were no developments as far as I can tell:
https://sourceforge.net/p/refind/discussion/general/thread/60e840f4/
https://sourceforge.net/p/refind/discussion/general/thread/c91b84cfd7/

Due to this, it is not possible to boot a disk image directly from refind. The only solution would be to chainload a grub bootloader located in your efi partition that would load the linuxloops generated configuration but it is quite complex:
- From a linux distro with grub installed, create a grub bootloader efi file that will load its grub configuration from the current directory it is in:
`grub-mkimage -O x86_64-efi -o ./grubx64.efi -p "" all_video boot btrfs cat chain configfile echo efifwsetup efinet ext2 fat font gettext gfxmenu gfxterm gfxterm_background gzio halt help hfsplus iso9660 jpeg keystatus linux loadenv loopback ls lsefi lsefimmap lsefisystab lssal memdisk minicmd normal ntfs part_apple part_msdos part_gpt password_pbkdf2 png probe reboot regexp search search_fs_uuid search_fs_file search_label sleep smbios squash4 terminal test true video xfs zfs zfscrypt zfsinfo`
- Copy the grub configuration provided by the linuxloops script as grub.cfg and add at the top "set timeout=0" so that the config is booted without showing the grub bootloader.
- Install both files in a directory in your efi partition like "/EFI/ChromeOS-Flex" for example.
- From there I think refind should detect the new grub bootloader automatically or you can potentially make a specific config to chainload it.

**Comment by emilieroberts** [comment]
Thanks for the response, that's a good starting point. I'll take a stab at it, I remember chainloading like this at some point in the past. I will post here if I have some success. I think we can close this for now?
