### ISSUE TITLE
tried to run on OpenSUSE Leap 15.6 to no effect

### ISSUE THREAD

**Issue by csp5me** [sebanc/linuxloops#19]
No big priority for me. 
But in README I read - "Linuxloops can be used from any Linux distribution" .

I think the script has been tested in primarily debian like Linux, e.g. chown {user} {user} is specific Debian, while OpenSUSE uses {user} / users for user accounts and groups. So I got a chown invalid group error.

After I fixed this, the tool just stopped. Zenity was installed.

Proposed solution - change README, saying on which distro the script has been tested. I have tested it to work on Debian, LMDE and Ubuntu.

**Comment by sebanc** [comment]
I cannot test linuxloops with all distributions / versions but linuxloops only use very basic linux functions that are available in all distros so I assume it works unless told otherwise.
You raise a good point, the script should use the primary group id instead of assuming it is the same as the user id, I have just fixed this.

I will try to install OpenSUSE Leap 15.6 and see if there are other bugs.

**Comment by sebanc** [comment]
Fixed.
OpenSUSE Leap needs sudo to be called with "-E" option to start zenity correctly. It seems like a good practice so I added it to the instructions.
