### ISSUE TITLE
any plans on doing a tutorial on how to modify arch linux to steamos? Really like to modify myself, not using another distro.

### ISSUE THREAD

**Issue by Ktsuruta196** [sebanc/linuxloops#4]

**Comment by sebanc** [comment]
I don't think a tutorial would be suited for this as the process just consist in adding configuration files to archlinux.

The tutorial would be:
- Make sure that you have polkit, sddm, plasma, gamescope and steam installed.
- The code to create the needed configuration files is between the lines containing `cat >"$linuxloopsdir"/chroot/tmp/install_steamos_fixes <<STEAMOSLIKEFIXES` and  `STEAMOSLIKEFIXES` text (currently lines 5657 and 6200 of the linuxloops script). Copy it into a bash script.
- Change "$username" in the bash script to your user name.
- Run the bash script with sudo.
- Run `cp /etc/skel/Desktop/GamingSession.desktop ~/Desktop/` 
- Reboot
- Your pc should boot directly to plasma and you should have a GamingSession icon to launch the SteamOS gamescope session.

Nevertheless, the packages / configuration files that you currently have on your archlinux install could not play well with this and might result in an unbootable system (which is why I think it is easier to just run the linuxloops script to perform a clean archlinux install with those configuration files included and start from there).
