### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by lavilao** [sebanc/linuxloops#7]
Hi, I have a few questions if you dont mind:
-how can I make so the clock in linux is the same as in chromeos flex? its annoying having to change it every time
-how hard would it be to add support for fydeos/openfyde?
-if I edited the installer to use a fydeos image instead of the chromeos flex one would it work?
-is it safe to auto-update chromeos flex?
-I used a .img file to install chromeos flex, in case of a update wanting to delete everything: would delete every other partition of the drive or just fuck up the .img file?
Thanks in advice!

**Comment by sebanc** [comment]
Hi,

1) Maybe I am missing something but I don't remember having this issue. Is your clock set to UTC time in your bios ?

2) I have never looked at fydeos/openfyde images, I guess that adding them would indeed not be very different from ChromeOS-Flex. However, I feel responsible to only allow the installation of trusted software and there are rumours about fishy telemetry in FydeOS (I do not have a personal opinion on this topic). OpenFyde is also not completely open source. If there were trusted resources that would confirm Fyde is safe, I could work on adding them but for now I will avoid it.

3) Updates in ChromeOS-Flex images should be quite safe as linuxloops makes very few mofications to be able to boot from an image. Since I implemened ChromeOS-Flex several versions ago, I had no issues with it. However, I cannot provide any guarantee so make sure you have a backup of important data at all times.

4) I don't think ChromeOS-Flex booted from an image could wipe the entire drive but again I cannot provide any guarantee.

**Comment by lavilao** [comment]
First: Happy new year!
1: I think I have set it to utc, in linux and windows I use the hardware clock and these dont change when I reboot.
2: FydeOS is indeed not open source, openfyde however it is https://github.com/openFyde/overlay-amd64-openfyde. There is telemetry in FydeOS (not openfyde), calling it fishy when they put you a eula before installing telling you that they have telemetry but again nobody reads an eula 😄. For resources I would guess their community forums and telegram channel would be in favor of it and non users forums would be "china bad" so cant provide anything more than my testimony.
3-4: I have been investigating and fydeos supports dual boot by using the same approach you use, use a img file mounted as a drive, and they claim that neither updates nor powerwash will touch the other files in your drive.

**Comment by sebanc** [comment]
Regarding 1, my understanding is that your hardware clock is set to localtime and that you use UTC timezone in linux to have the correct time information, however chromeos-flex sets the timezone automatically. The only way I found to have correct time between different OS is to make windows use UTC:
https://wiki.archlinux.org/title/System_time#UTC_in_Microsoft_Windows

For 2, I understand your point and I have personnally nothing against Fyde but I will wait for Fyde to be more recognized as a safe solution.

**Comment by lavilao** [comment]
1: thanks
2: ok, thanks
